In [1]:
4 + 6

10

In [2]:
34*46

1564

In [3]:
a = 234

In [4]:
a

234

In [5]:
print(a)

234


In [6]:
range(5)

range(0, 5)

In [9]:
for i in range(3,5):
    print(f"Hello {i}")

Hello 3
Hello 4


In [10]:
# Python comment

# Heading 1

normal text
* List item 1
* List item 2

## Heading 2
[Link description](https://www.andreasjakl.com/)

In [11]:
import numpy as np

In [13]:
np.sin(90)

0.8939966636005579

In [14]:
np.sin?

Call signature:  np.sin(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'sin'>
File:            c:\users\marce\anaconda3\lib\site-packages\numpy\__init__.py
Docstring:      
sin(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Trigonometric sine, element-wise.

Parameters
----------
x : array_like
    Angle, in radians (:math:`2 \pi` rad equals 360 degrees).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see 

In [16]:
np.sin(np.pi/2.0)

1.0

In [18]:
np.int64(64646464646464646464646464646464646464646464646464646464646464646464646464646)

OverflowError: int too big to convert

In [20]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [21]:
type(arr[1])

numpy.int32

In [22]:
arr * arr

array([1, 4, 9])

In [23]:
mat = np.array([[1,2,3], [4,5,6], [7,8,9]])
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
vec = np.arange(12).reshape(4,3)
vec

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
vec2 = vec.reshape(3,4)
vec2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
vec[1,1] = 99
vec

array([[ 0,  1,  2],
       [ 3, 99,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
vec2[0]

array([0, 1, 2, 3])

In [29]:
vec2[1,1]

5

In [30]:
vec[:,2]

array([ 2,  5,  8, 11])

In [31]:
vec2[2:,1]

array([9])

In [32]:
mat5 = np.arange(5)
mat5

array([0, 1, 2, 3, 4])

In [33]:
mat5[3]

3

In [34]:
mat5[np.array([True, False, True, False, True])]

array([0, 2, 4])

In [35]:
mat5 > 1

array([False, False,  True,  True,  True])

In [36]:
mat5[mat5 <= 3]

array([0, 1, 2, 3])

In [38]:
mat5[(mat5 < 1) | (mat5 > 2)]

array([0, 3, 4])

In [51]:
mat5[(mat5 > 1) & (mat5 <3)]



array([2])

In [52]:
rnd = np.random.rand(4,5)
rnd

array([[0.07284385, 0.26285155, 0.13356655, 0.50966727, 0.96491667],
       [0.65522648, 0.70836534, 0.60525855, 0.1451324 , 0.32054779],
       [0.57948589, 0.73148192, 0.48747018, 0.71547729, 0.99309008],
       [0.6617266 , 0.89328562, 0.20463955, 0.90374119, 0.72983791]])

In [53]:
np.mean(rnd)

0.5639306335490895

In [54]:
np.median(rnd)

0.6302425134261773

In [55]:
np.std(rnd)

0.28086695971824766

In [56]:
rnd > np.mean(rnd)

array([[False, False, False, False,  True],
       [ True,  True,  True, False, False],
       [ True,  True, False,  True,  True],
       [ True,  True, False,  True,  True]])

In [57]:
rnd[rnd>np.mean(rnd)]

array([0.96491667, 0.65522648, 0.70836534, 0.60525855, 0.57948589,
       0.73148192, 0.71547729, 0.99309008, 0.6617266 , 0.89328562,
       0.90374119, 0.72983791])

In [58]:
rnd.mean

<function ndarray.mean>

In [59]:
rnd.mean(
)

0.5639306335490895